#!/bin/bash
# MQTT settings
BROKER="10.0.0.99"
TOPIC="hiveos/dell"
USER=""
PASS=""

# Ensure mosquitto-clients is installed
dpkg -s mosquitto-clients >/dev/null 2>&1 || apt update && apt install -y mosquitto-clients

# Stream logs to MQTT
tail -f /var/log/hive-agent.log | while read -r line; do
    json_line=$(echo ${line} | awk -F'[<>]' {'print $2'})
    if $(echo "$json_line" | jq -e 'has("method")'); then
        mosquitto_pub -h $BROKER -t $TOPIC -u "$USER" -P "$PASS" -m "$json_line"
    fi
done





########## FOLLWING CODE ARE COMMANDS ########
mkdir buddy_scripts
nano buddy_mqtt.sh
chmod +x buddy_mqtt.sh
bash buddy_mqtt.sh
nano /hive/etc/crontab.root

@reboot sleep 900 && /opt/buddy_scripts/buddy_mqtt.sh
